import test from 'node:test';
import assert from 'node:assert/strict';
import { check, findAttribution, stripToolFooter, subjects } from '../scripts/check-attribution.mjs';

const footer = '\n\n---\n_Generated by [Claude Code](https://claude.ai/code/session_01AbCdEf)_';

test('attribution finds a co-author trailer naming a tool or vendor', () => {
  for (const trailer of [
    'Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>',
    'co-authored-by: Codex <codex@openai.com>',
    'Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>',
    'Co-Authored-By: Gemini <gemini@google.com>',
  ]) {
    const found = findAttribution(`Let a person change their name\n\nBody text.\n\n${trailer}`);
    assert.equal(found.length, 1, trailer);
    assert.match(found[0].reason, /Co-Authored-By/);
  }
});

test('attribution leaves a co-author trailer naming a person alone', () => {
  assert.deepEqual(findAttribution('Fix the date picker\n\nCo-Authored-By: Devin Rao <devin@example.com>'), []);
});

test('attribution finds a generated-with footer and a session link', () => {
  const generated = findAttribution('## What changed\n\nStuff.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)');
  assert.deepEqual(generated.map((finding) => finding.reason), ['a "Generated with/by" line naming an AI tool or vendor']);
  const link = findAttribution('Notes\n\nhttps://claude.ai/code/session_01AbCdEf');
  assert.deepEqual(link.map((finding) => finding.reason), ['a claude.ai/code session link']);
});

test('attribution does not flag prose that only mentions the rule', () => {
  const prose = 'No `Co-Authored-By:` trailer naming a tool, no "Generated with ..." footer.\nThe schema is generated by the migration script.';
  assert.deepEqual(findAttribution(prose), []);
  assert.deepEqual(findAttribution(''), []);
  assert.deepEqual(findAttribution(undefined), []);
});

test('stripping removes the tooling footer and nothing else', () => {
  const body = '## What changed\n\nA real paragraph.\n\n---\n\nA rule the author drew.';
  assert.equal(stripToolFooter(`${body}${footer}`), body);
  assert.equal(stripToolFooter(`${body}\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n`), body);
  assert.equal(stripToolFooter(`${body}\n\nhttps://claude.ai/code/session_01AbCdEf\n`), body);
  assert.equal(stripToolFooter(body), body);
  assert.equal(stripToolFooter(''), '');
});

test('stripping leaves a footer worded any other way for the check to fail on', () => {
  const body = 'Text.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code) by the session';
  assert.equal(stripToolFooter(body), body);
  assert.equal(findAttribution(stripToolFooter(body)).length, 1);
});

test('a pull request is read through its title, cleaned body and own commits', () => {
  const event = {
    pull_request: {
      title: 'Let a person change their name',
      body: `Plain description.${footer}`,
      base: { ref: 'main', sha: 'b'.repeat(40) },
      head: { sha: 'a'.repeat(40) },
    },
  };
  let range;
  const readCommits = (...args) => {
    range = args;
    return [{ sha: 'c'.repeat(40), message: 'Change the name\n\nCo-Authored-By: Claude <noreply@anthropic.com>' }];
  };
  const items = subjects('pull_request', event, readCommits, () => true);
  assert.deepEqual(range, ['a'.repeat(40), '^origin/main']);
  assert.equal(items.find((item) => item.where === 'PR body').text, 'Plain description.');
  assert.deepEqual(check(items).map((finding) => finding.where), ['commit ccccccc']);
});

test('a push reads the pushed range, or only the head when there is no earlier commit', () => {
  const ranges = [];
  const readCommits = (...args) => {
    ranges.push(args);
    return [];
  };
  subjects('push', { before: '1'.repeat(40), after: '2'.repeat(40) }, readCommits, () => true);
  subjects('push', { before: '0'.repeat(40), after: '2'.repeat(40) }, readCommits, () => true);
  assert.deepEqual(ranges, [[`${'1'.repeat(40)}..${'2'.repeat(40)}`], ['2'.repeat(40), '-1']]);
});
